// Battlecards — rendered from the battlecards table (generated by Claude
// in-session locally, or by the Claude API on a schedule in production).
// Falls back to the "what this needs" stub if none have been generated yet.
import { getDb } from '@/db/client';
import { Soon } from '@/lib/soon';
import { requireOrgId } from '@/lib/tenant';

export const dynamic = 'force-dynamic';

interface Card {
  positioning: string;
  strengths: string[];
  vulnerabilities: string[];
  howToWin: string[];
  keyQuestion: string;
}

function ago(iso: string): string {
  const d = Date.now() - new Date(iso).getTime();
  const h = Math.floor(d / 3600000);
  if (h < 1) return 'just now';
  if (h < 24) return `${h}h ago`;
  return `${Math.floor(h / 24)}d ago`;
}

export default async function Battlecards() {
  const orgId = await requireOrgId();
  const db = await getDb();
  const rows = await db.query<{ name: string; slug: string; content: Card | string; generated_at: string; generated_by: string }>(
    `SELECT c.name, c.slug, b.content, b.generated_at, b.generated_by
     FROM battlecards b JOIN competitors c ON c.id = b.competitor_id WHERE c.org_id = $1 ORDER BY c.id`,
    [orgId],
  );
  if (rows.length === 0) {
    return (
      <Soon
        title="Battlecards"
        blurb="Auto-generated, self-updating sales battlecards per competitor."
        needs="run `npm run battlecards` (Claude in-session) or set ANTHROPIC_API_KEY in production"
        bullets={[
          'Positioning, strengths, vulnerabilities, how-to-win and the discovery-call question per competitor.',
          'Numbers pulled live from captured signals; strategy authored by Claude.',
        ]}
      />
    );
  }
  const gen = rows[0];
  return (
    <main className="main solo">
      <section className="feed">
        <h1>Battlecards</h1>
        <p className="sub">
          Generated by Claude from captured signals · updated {ago(gen.generated_at)}. Numbers are live; strategy
          regenerates automatically once the API layer runs on a schedule.
        </p>
        {rows.map((r) => {
          const c = (typeof r.content === 'string' ? JSON.parse(r.content) : r.content) as Card;
          return (
            <div className="bc" key={r.slug}>
              <div className="bc-head">
                <span className="comp">{r.name}</span>
                <a className="bc-link" href={`/feed?comp=${r.slug}`}>view signals →</a>
              </div>
              <p className="bc-pos">{c.positioning}</p>
              <div className="bc-grid">
                <div className="bc-col strengths">
                  <h4>Their strengths</h4>
                  <ul>{c.strengths.map((s, i) => <li key={i}>{s}</li>)}</ul>
                </div>
                <div className="bc-col vulns">
                  <h4>Vulnerabilities</h4>
                  <ul>{c.vulnerabilities.map((s, i) => <li key={i}>{s}</li>)}</ul>
                </div>
                <div className="bc-col win">
                  <h4>How we win</h4>
                  <ul>{c.howToWin.map((s, i) => <li key={i}>{s}</li>)}</ul>
                </div>
              </div>
              <div className="bc-q"><span>Ask in discovery</span>{c.keyQuestion}</div>
            </div>
          );
        })}
      </section>
    </main>
  );
}
