// Battlecards — where the reasoning lives. Each card opens with "The read":
// one whole-picture synthesis per competitor (competitor_reasoning, authored
// by Claude in-session or live via API) connecting every signal on file —
// moves, buildouts, hiring — into what's actually happening. Below it, the
// card's three angles (sales / marketing / product) because a rep, a
// marketer, and a PM need different things from the same intelligence.
// Falls back to the "what this needs" stub if none generated.
import { getDb } from '@/db/client';
import { Soon } from '@/lib/soon';
import { requireOrgId } from '@/lib/tenant';
import { getCompetitorReads } from '@/lib/reason';
import { isPlatformAdmin } from '@/lib/adminAuth';
import FeedbackControl from '../FeedbackControl';

export const dynamic = 'force-dynamic';

interface Angle { focus: string; points: string[]; action: string }
interface Card {
  positioning: string;
  strengths: string[];
  vulnerabilities: string[];
  howToWin: string[];
  keyQuestion: string;
  angles?: { sales: Angle; marketing: Angle; product: Angle };
}

function ago(iso: string): string {
  const d = Date.now() - new Date(iso).getTime();
  const h = Math.floor(d / 3600000);
  if (h < 1) return 'just now';
  if (h < 24) return `${h}h ago`;
  return `${Math.floor(h / 24)}d ago`;
}

const ANGLE_META = {
  sales: { label: 'Sales', cls: 'ang-sales' },
  marketing: { label: 'Marketing', cls: 'ang-marketing' },
  product: { label: 'Product', cls: 'ang-product' },
} as const;

export default async function Battlecards() {
  const orgId = await requireOrgId();
  const reads = await getCompetitorReads(orgId);
  const platformAdmin = await isPlatformAdmin();
  const db = await getDb();
  const rows = await db.query<{ name: string; slug: string; content: Card | string; generated_at: string; generated_by: string }>(
    `SELECT c.name, c.slug, b.content, b.generated_at, b.generated_by
     FROM battlecards b JOIN competitors c ON c.id = b.competitor_id WHERE c.org_id = $1 ORDER BY c.id`,
    [orgId],
  );
  if (rows.length === 0) {
    return (
      <Soon
        title="Battlecards"
        blurb="Auto-generated, self-updating battlecards per competitor, from three angles: sales, marketing, product."
        needs="run `npm run battlecards` (Claude in-session) or set ANTHROPIC_API_KEY in production"
        bullets={[
          'Positioning, strengths, vulnerabilities, how-to-win and the discovery-call question per competitor.',
          'Sales, Marketing, and Product each get a distinct read of the same intelligence.',
          'Numbers pulled live from captured signals; strategy authored by Claude.',
        ]}
      />
    );
  }
  const gen = rows[0];
  const initials = (name: string) => name.split(/\s+/).map((w) => w[0]).join('').slice(0, 2).toUpperCase();
  return (
    <main className="main solo">
      <section className="feed">
        <h1>Battlecards</h1>
        <p className="sub">
          One card per competitor, read from three angles — Sales, Marketing, Product — from the same underlying
          intelligence. Numbers pull from live signals · strategy generated by Claude · updated {ago(gen.generated_at)}.
        </p>
        {rows.map((r) => {
          const c = (typeof r.content === 'string' ? JSON.parse(r.content) : r.content) as Card;
          const read = reads.get(r.slug);
          return (
            <div className="bc" key={r.slug}>
              <div className="bc-head">
                <span className="cc-avatar sm">{initials(r.name)}</span>
                <span className="comp">{r.name}</span>
                <a className="bc-link" href={`/feed?comp=${r.slug}`}>view signals →</a>
              </div>
              {read && (
                <div className="bc-read">
                  <div className="bc-read-top">
                    <span className="bc-read-tag">The read</span>
                    <span className="bc-read-hook">{read.hook}</span>
                  </div>
                  <p className="bc-read-body">{read.narrative}</p>
                  {read.evidence.length > 0 && (
                    <div className="bc-read-ev">
                      {read.evidence.map((e, i) => (
                        <span className="bc-read-chip" key={i}><b>{e.label}</b> {e.text}</span>
                      ))}
                    </div>
                  )}
                  {platformAdmin && (
                    <FeedbackControl competitorName={r.name} channel="read" signalTitle={`competitor read: ${r.name}`} headlineShown={read.narrative.slice(0, 300)} />
                  )}
                </div>
              )}
              <p className="bc-pos">{c.positioning}</p>
              <div className="bc-grid">
                <div className="bc-col strengths">
                  <h4>Their strengths</h4>
                  <ul>{c.strengths.map((s, i) => <li key={i}>{s}</li>)}</ul>
                </div>
                <div className="bc-col vulns">
                  <h4>Vulnerabilities</h4>
                  <ul>{c.vulnerabilities.map((s, i) => <li key={i}>{s}</li>)}</ul>
                </div>
                <div className="bc-col win">
                  <h4>How we win</h4>
                  <ul>{c.howToWin.map((s, i) => <li key={i}>{s}</li>)}</ul>
                </div>
              </div>
              <div className="bc-q"><span>Ask in discovery</span>{c.keyQuestion}</div>

              {c.angles && (
                <div className="bc-angles">
                  {/* JSONB doesn't preserve object key order (Postgres reorders by key
                      length), so render in a fixed, intentional sequence rather than
                      trusting Object.entries. */}
                  {(['sales', 'marketing', 'product'] as const).map((key) => {
                    const a = c.angles![key];
                    return [key, a] as [keyof typeof ANGLE_META, Angle];
                  }).map(([key, a]) => (
                    <div className={`bc-angle ${ANGLE_META[key].cls}`} key={key}>
                      <span className="bc-angle-tag">{ANGLE_META[key].label}</span>
                      <p className="bc-angle-focus">{a.focus}</p>
                      <ul>{a.points.map((p, i) => <li key={i}>{p}</li>)}</ul>
                      <div className="bc-angle-action"><span>Do this</span>{a.action}</div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          );
        })}
      </section>
    </main>
  );
}
